### ISSUE TITLE
TE-153 : Import Exam (TE-147)

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#153]
pull request : 
https://git.camelcasetech.com/camelCase/testing-engine/pulls/78

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 
when try to import Exam this error is display
![importtest](https://user-images.githubusercontent.com/12035045/27383963-75460b6c-568d-11e7-9ef1-04f40ea0f1b6.png)

**Comment by badr4php** [comment]
new pull request to compare with develop 
https://git.camelcasetech.com/camelCase/testing-engine/pulls/83

**Comment by solimansamy** [comment]
@badr4php I followed the scenario below

1. Create a test from admin panel.
2. Export the test.
3. Import the same test.
4. Test is created but exception raised.
```
Sorry, it seem like a problem happened while trying to access this page, please contact the administrator.
SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `tags` (`count`, `updated_at`, `created_at`) values (1, 2017-07-06 16:11:18, 2017-07-06 16:11:18))
#0 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('insert into `ta...', Array, Object(Closure))
#1 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Connection.php(481): Illuminate\Database\Connection->run('insert into `ta...', Array, Object(Closure))
#2 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Connection.php(435): Illuminate\Database\Connection->statement('insert into `ta...', Array)
#3 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `ta...', Array)
#4 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2154): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ta...', Array, 'id')
#5 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1470): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1609): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1574): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1471): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /home/vagrant/testing-engine/modules/admin/Tests/Models/Tests.php(143): Illuminate\Database\Eloquent\Model->save()
#10 /home/vagrant/testing-engine/modules/admin/Tests/Models/TestsImport.php(43): App\Admin\Tests\Models\Tests->saveTags(Object(App\Entities\Tests\Test), NULL)
#11 /home/vagrant/testing-engine/modules/admin/Tests/Http/Controllers/TestsController.php(335): App\Admin\Tests\Models\TestsImport->importTest(Object(Illuminate\Http\Request))
#12 [internal function]: App\Admin\Tests\Http\Controllers\TestsController->importPost(Object(App\Admin\Tests\Models\TestsImport))
#13 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#14 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('importPost', Array)
#15 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Admin\Tests\Http\Controllers\TestsController), 'importPost')
#16 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#17 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/vagrant/testing-engine/app/Http/Middleware/Authorize.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\Authorize->handle(Object(Illuminate\Http\Request), Object(Closure), 'manage-tests')
#21 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/vagrant/testing-engine/modules/admin/Base/Http/Middleware/Menu.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Admin\Base\Http\Middleware\Menu->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/vagrant/testing-engine/modules/admin/Base/Http/Middleware/AdminTheme.php(20): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Admin\Base\Http\Middleware\AdminTheme->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/vagrant/testing-engine/app/Http/Middleware/Acl.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\Acl->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/vagrant/testing-engine/app/Http/Middleware/Localization.php(20): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/vagrant/testing-engine/app/Http/Middleware/LogAfterRequest.php(15): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\LogAfterRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#61 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#62 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#63 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#64 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /home/vagrant/testing-engine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /home/vagrant/testing-engine/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 {main}
```

**Comment by badr4php** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/119
